.\"                                      Hey, EMACS: -*- nroff -*-
.TH GARMIN-FORERUNNER-TOOLS 1 "March 31, 2008"
.SH NAME
garmin_gmap \- convert .gmn files into xml data
.SH SYNOPSIS
.B garmin_dump
.I file
.PP
\fBgarmin_dump\fP reads a .gmp file as produced by \fBgarmin_save_runs\fP,
and writes its translation into XML to standard output.
.SH SEE ALSO
.BR garmin_get_info (1),
.BR garmin_save_runs (1),
.BR garmin_gmap (1).
.br
.SH AUTHOR
garmin_get_info was written by Dave Bailey.
