.\"                                      Hey, EMACS: -*- nroff -*-
.TH GARMIN-FORERUNNER-TOOLS 1 "March 31, 2008"
.SH NAME
garmin_gpx \- convert .gmn files into xml data for use with OpenStreetMap
.SH SYNOPSIS
.B garmin_gpx
.I file
.PP
\fBgarmin_gpx\fP reads a .gmp file as produced by \fBgarmin_save_runs\fP, and
writes to standard output the xml representation (for
OpenStreetMap maps).
.SH SEE ALSO
.BR garmin_get_info (1),
.BR garmin_save_runs (1),
.BR garmin_dump (1).
.br
.SH AUTHOR
garmin_gpx was written by Chris AtLee.
