.\"                                      Hey, EMACS: -*- nroff -*-
.TH GARMIN-FORERUNNER-TOOLS 1 "March 31, 2008"
.SH NAME
garmin_get_info \- retrieve basic information from a Forerunner device.
.SH SYNOPSIS
.B garmin_get_info
.PP
\fBgarmin_get_info\fP retrieves basic information from a Garmin Forerunner
device connected to an USB port, such as its software version
and supported protocols.	
.SH SEE ALSO
.BR garmin_save_runs (1),
.BR garmin_dump (1),
.BR garmin_gmap (1).
.br
.SH AUTHOR
garmin_get_info was written by Dave Bailey.

